### PR TITLE
Moving source-api to core module

### LINKED ISSUE #41: Move Source Module to Core Module
I think it would be better to move the source module to core, because the source module is depend on core because of  Dependencies class and every extension implement the source and core class together and also their dependencies are same, so I think moving the source files to core can be better choice.

also please add this line to core module build.gradle.kts, 

```
kotlin {
...
android {
    publishLibraryVariants("release", "debug")
  }
..
```
in order to publish android packages to snapshot in additional to desktop and jvm

### PR DESCRIPTION
**Pull request by kazemcodes**
Closes #41 

because sources are dependant on core module , I think it's better to put the source-api in core because almost all the time when we implement the source api and core at the same time and as they are dependent on each other we can only implement them in gradle by compileOnly and because of that some problems may occurs like. all in all I think its better to put them in one package. 
also I added the publishLibraryVariants so that there will be an android maven publish.

this is my first pull request, so if there's problem in that, let me know.

### CODE REVIEW

**Comment by arkon** [comment]
@inorichi Any thoughts?

**Comment by inorichi** [comment]
I don't understand why this is needed. First of all, the dependency on the core/source-api modules is hidden behind [this file](https://github.com/tachiyomiorg/tachiyomi-extensions-1.x/blob/master/buildSrc/src/main/kotlin/extension-setup.gradle.kts). You shouldn't ever need to specify them when using the [Extension](https://github.com/tachiyomiorg/tachiyomi-extensions-1.x/blob/master/samples/single-site/build.gradle.kts) class in build.gradle files.

> we can only implement them in gradle by compileOnly and because of that some problems may occurs like.

Can you elaborate this line? Which problems are you referring to?

**Comment by kazemcodes** [comment]
Actually, I use your project for tachiyomi 1.x extension to create extensions for my app( extensions are working great not sure why you said they are not working in reader,  and also do I need to mention tachiyomi name somewhere in my project )when implementing both source module and core module at the same time,  because both app use same dependency, so the gradle throws Duplicate dependency for example there is two httpclients, because of that you can not use implemention and need to use the compileOnly. 
Another point is because source module dependency on core module, putting them in same module is a lot better. There is no need to publish them separately.

**Comment by kazemcodes** [comment]
you are right. it would add unnecessary complexity to the app, but I think, you need to find a way to exclude dependencies that aren't the Android variants someway.

**Pull request closed without merging**
