### PR TITLE
Update Manga screen

### PR DESCRIPTION
**Pull request by ghostbear**
Couldn't figure how to get ConstraintLayout to work with Kotlin Multiplatform so scrim is missing and chevron is not placed over description when collapsed

| Before | After |
|---|---|
| Screenshot_1639332196 | Screenshot_1639331504 |
| Screenshot_1639332200 | Screenshot_1639332090 |
| - | Screenshot_1639332094 |
| - | Screenshot_1639332097 |
| Screenshot_1639333299 | Screenshot_1639333388 |

### CODE REVIEW

**Comment by inorichi** [comment]
Can you explain a bit what you wanted to achieve with ConstraintLayout? Maybe we can use a Layout and manually place the children (as I did for the catalog item)?

CL for desktop is still "assigned" sadly: https://issuetracker.google.com/issues/196872024

Worst case we can use expect/actual and just ignore the desktop version for now, as there are still many things missing like navigation for a desktop app.

**Comment by ghostbear** [comment]
> Can you explain a bit what you wanted to achieve with ConstraintLayout?

For the layout, I wanted a scrim (fade) and the expand/collapse button to be placed on top of the description when the state is collapsed and otherwise when it is expanded scrim becomes invisible, and the expand/collapse button gets placed under the description. So with ConstraintLayout, it would be an if statement to change the position/constraints of the button.

> Maybe we can use a Layout and manually place the children (as I did for the catalog item)?

Could probably work, will look into it

---

What I wanted to achieve more or less

| Collapsed | Expanded |
|---|---|
| Screenshot_20211214-134545 | Screenshot_20211214-134551 |

**Comment by inorichi** [comment]
Oh, I see. I think it should not be too difficult with `Layout`: 

We have 3 situations (TH = text height; IH = icon height; LH = layout height; X = some height threshold in dp):

measure TH and then
* if TH <= X:
  * LH = TH; no icon
* if TH > X (icon Y position is always LH - IH):
  * if collapsed:
    * LH = X; TH = clip to X
  * if expanded:
    * LH = TH + IH; TH = fill

Not sure if it's possible to implement a content animation with this approach though.

**Comment by ghostbear** [comment]
Think I got something like that implemented in #38, it doesn't go by a threshold though but rather the expanded state. Now that you mention I can get the number of lines after measuring I think it will be good to check the number of lines because if it's less than 3 it will look wonky so should probably not have the scrim then or the button.

As for content animation, I think just slapping `animateContentSize` modifier gives an animation but could also just be placebo

**Pull request merged**
