### PR TITLE
Add scrim and use Layout to place composables manually 

### PR DESCRIPTION
**Pull request by ghostbear**
| Less or equal to three lines | Collapsed | Expanded |
|---|---|---|
 | Screenshot_1639504854 | Screenshot_1639504867 | Screenshot_1639504871 |

### CODE REVIEW

**Comment by inorichi** [comment]
Looks quite nice!

We can probably go with a single `Text` component with something like this:


```kt
// ... in the MangaSummaryDescription composable
var isExpandable by remember { mutableStateOf(false) }

// ... in Layout/SubcomposeLayout
Text(
  text = text,
  modifier = ...,
  onTextLayout = { layoutResult ->
    isExpandable = layoutResult.lineCount > COLLAPSED_MAX_LINES
  }
```

But I don't know if it's actually feasible like this as it seems the layout will need to invalidate itself the first round.

**Comment by ghostbear** [comment]
As you say it will invalidate itself the first round and it will cause the summary to do a shrink animation (if it's tall enough) like if the user were to collapse when expanded, which looks weird. One way to get around this would be to do an empty draw the first round, which would cause a small grow animation (less noticeable).

`onTextLayout` is probably needed in some way regardless of implementation to tell the genre `Row` to be expanded when the summary is not expandable

**Comment by inorichi** [comment]
I'll play around with it and try to fix the animation.

**Comment by inorichi** [comment]
I'm seeing this crash randomly:

`java.lang.IllegalStateException: Place was called on a node which was placed already`

Not sure if it's related to this PR as the trace does not include any line from our code. Have you noticed it before?

**Comment by ghostbear** [comment]
I haven't noticed before `java.lang.IllegalStateException: Place was called on a node which was placed already`

However, I have noticed frequent crashes when opening the manga screen (`NullPointerException` in `MangaViewModel`) or leaving it when browsing (duplicate `key` error when Browsing old MangaDex extensions) but it has happened before this PR as well. For opening the manga screen stacktrace says something like params being null, the line that causes it: https://github.com/tachiyomiorg/tachiyomi-1.x/blob/b7e168b7177df91906ed984437538074f693f3f2/presentation/src/commonMain/kotlin/manga/MangaViewModel.kt#L50

**Comment by inorichi** [comment]
I've reworked a bit this at https://github.com/tachiyomiorg/tachiyomi-1.x/commit/3e47698f3c2bf107672c8bee5eac0368fede7f35.

The `isExpandable` property is now nullable to represent the unknown state (before the first measurement). We use that to remove the `.animateContentSize()` modifier when we do not know if it's expandable.

I made use of `didOverflowHeight` on the text layout result rather than `lineCount` in order to use `maxLines` on the `Text` component, so it's not needed to calculate line heights.

I also reverted from `SubcomposeLayout` to `Layout` as it's simpler and has better performance.


When the screen is opened, the text is initially limited to 3 lines now, so you won't see a frame (although it's difficult to notice) with a big wall of text now.

Regarding the crash, it's this one: https://issuetracker.google.com/issues/208855077

**Pull request merged**
